### ISSUE TITLE
Class '\backend\models\User' not found

### ISSUE THREAD

**Issue by shilecro** [WadeShuler/yii2-members-system#2]
Installed yii2-members-system as described and when I try to change password in backend yii throws exception

Class '\backend\models\User' not found
 in ...../html/yii2-members/vendor/yiisoft/yii2/validators/UniqueValidator.php

**Comment by WadeShuler** [comment]
Sorry, I will check it out and fix it. I opened this project up publicly so that I could get issues like this and fix them. Letting the community help me find and squash the bugs. Most features should be pretty solid.

This one looks like it was from moving things around, because it should be `common\models\User`.

**Comment by shilecro** [comment]
No problem, glad to help

**Comment by WadeShuler** [comment]
It is fixed in the latest release.

backend/models/Admin.php (line 74)

    ['email', 'unique', 'targetClass' => '\backend\models\Admin', 'message' => 'This email address has already been taken.'],

It was referencing `\backend\models\User` for some reason.

I also fixed up the Codeception tests.
