### ISSUE TITLE
stored xss vulnerability

### ISSUE THREAD

**Issue by webremote** [WadeShuler/yii2-members-system#4]
### What is the issue?
no proper checks on profile fields input/output causes stored xss vulnerability
 

### Additional Information
see the demo, updated one field with simple `'"><script>alert(1)</script>` which is now visible throughout the demo (sorry...)

| Q                | A
| ---------------- | ---
| Yii2 Version     | -
| Yii2 Marketing System Version | -
| PHP version      | -
| Operating system | -

**Comment by WadeShuler** [comment]
This has been fixed in the latest release. Thank you for bringing it to my attention. I apologize for the delay, I have been pretty busy, and it was a simple fix that I am sure anyone who noticed encoded them manually.

Anyone else reading this, you should be using the latest release (v2.0.7) on all new projects. On your old projects, please wrap all calls to echo `niceName` in the layout files (frontend, backend, mainsite) with `Html::encode()`.

This thread is closed. If you find anymore or I missed one you found, please open a new issue.

Thank You.
